logging:
  level:
    org.springframework.security: trace

spring:
  liquibase:
    enabled: true
    change-log: db.changelog/changelog-master.yaml


  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver